---
- name: 
  hosts: 192.168.1.161
  tasks: 

  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: root
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"
  - name: Set authorized key taken from file
    ansible.posix.authorized_key:
      user: sam
      state: present
      key: "{{ lookup('file', '/root/.ssh/id_rsa.pub') }}"

